# Generated by Django 3.0 on 2021-10-20 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_blood_group', models.CharField(max_length=60)),
                ('emp_mobile', models.BigIntegerField(unique=True)),
                ('emp_address', models.CharField(max_length=60)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Department')),
            ],
        ),
    ]
